### ISSUE TITLE
Vuex

### ISSUE THREAD

**Issue by AustineA** [ropbla9/vue-reactive-storage#7]
How do you use this inside Vuex or Middleware ?

**Comment by AustineA** [comment]
If anybody ever gets to this point. This is what i ended up doing in my auth middleware

`export default function (context) {
    if (process.client) {
      if (context.store.getters['auth/getUser']) {
      } else {
        return context.redirect('/login')
      }
    }
}
`

**Comment by solamichealolawale** [comment]
I don't see how this solve the problem of using localStorage in vuex file as it's displaying object as `[object]` in the Application Tab.
